events/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("create/", views.CreateEventView.as_view(), name="create_event"),
    path("submit/", views.submit_event, name="create_event"),
    path("<int:pk>/", views.EventView.as_view(), name="view_event"),
    path('<int:pk>/file/<int:file_id>/delete/', views.delete_event_file, name='delete_event_file'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('events/', include(("events.urls", 'events'), namespace="events")),
    path('organizations/', include('organizations.urls', namespace='organizations')),
    path('search/', include(("search.urls", 'search'), namespace="search")),
    path('upcoming/', include(("upcoming.urls", 'upcoming'), namespace="upcoming")),
    path('', include("myaccount.urls")),
    path('', include("pma.urls"))
]

pma/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('pma/', views.pma_page, name='pma'),
    path('pma/edit_event/<int:user_id>/', views.edit_event, name='edit_event'),
    path('pma/delete_event/', views.delete_event, name='delete_event'),
]

events/models.py
from django.db import models
from django.conf import settings
from myaccount.models import User
from organizations.models import Organization

import uuid



class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    location = models.CharField(max_length=200)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_events')
    organizations = models.ManyToManyField(Organization, related_name='events')

    # Recurrence Section
    is_recurring = models.BooleanField(default=False)
    # Options not required
    recurrence_frequency = models.CharField(max_length=10, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'),
                                                                    ('yearly', 'Yearly')], null=True, blank=True)
    recurrence_end = models.DateTimeField(null=True, blank=True)
    recurrence_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=False, null=True, blank=True)

    def get_recurrence_info(self):
        if self.is_recurring and self.recurrence_frequency:
            return f"Recurs {self.get_recurrence_frequency_display()}"
        return "Does Not Recur"

    def __str__(self):
        return f'{self.title} - {self.creator}'
    

def upload_file(instance, filename):
    return f'uploads/{instance.user.username}/{instance.event.id}/{filename}'


class EventFile(models.Model):
    event = models.ForeignKey(Event, related_name="files", on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    file = models.FileField(upload_to=upload_file)
    title = models.CharField(max_length=100, default="Untitled")
    description = models.TextField(blank=True, null=True)
    keywords = models.CharField(max_length=255, blank=True, null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def get_file_url(self):
        return f"https://{settings.AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/{self.file.name}"

    def __str__(self):
        return f'{self.file.name} for event: [{self.event.title}]'
    

class EventParticipant(models.Model):
    INVITED = 'Invited'
    CONFIRMED = 'Confirmed'
    DENIED = 'Denied'
    MAYBE = 'Maybe'

    STATUS_CHOICES = [
        (INVITED, 'Invited'),
        (CONFIRMED, 'Confirmed'),
        (DENIED, 'Denied'),
        (MAYBE, 'Maybe'),
    ]

    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user.username} - {self.event.title} - {self.status} - approved? {self.approved}'


class Comment(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.user.username} on {self.event.title} at {self.created_at}'
    

events/forms.py
import re
from django import forms
from events.models import Event, EventFile, EventParticipant, Organization
from myaccount.models import User
from django.core.exceptions import ObjectDoesNotExist


class CreateEventForm(forms.Form):
    title = forms.CharField(max_length=200)
    description = forms.CharField()
    location = forms.CharField(max_length=200, required=False)
    start_time = forms.DateTimeField()
    end_time = forms.DateTimeField()
    # Recurrence Section
    is_recurring = forms.BooleanField(required=False)
    recurrence_frequency = forms.ChoiceField(
        choices=[
            ('', 'Repeats:'),
            ('daily', 'Daily'),
            ('weekly', 'Weekly'),
            ('monthly', 'Monthly'),
            ('yearly', 'Yearly'),
        ],
        required=False
    )
    recurrence_end = forms.DateTimeField(required=False)
    def clean(self):
        cleaned_data = super().clean()
        start_time = cleaned_data.get('start_time')
        end_time = cleaned_data.get('end_time')

        if start_time and end_time and end_time < start_time:
            self.add_error("time", "End time cannot be earlier than start time.")
            
        if cleaned_data.get('is_recurring'):
            recurrence_end = cleaned_data.get('recurrence_end')
            if recurrence_end and recurrence_end < start_time:
                self.add_error("time","Recurrence end date cannot be earlier than the event start time.")

        return cleaned_data



class EventInviteUserForm(forms.Form):
    username = forms.CharField()
    error = None

    def is_invite_valid(self, event):
        try:
            user = User.objects.get(username=self.username)

            # Cannot invite yourself case
            if user == event.creator:
                self.error = "Error: You cannot invite yourself to your own event!"
                return False

            # Cannot invite someone already invited
            participants = EventParticipant.objects.filter(event=event)
            for participant in participants:
                if participant.username == self.username:
                    self.error = f'Error: {self.username} is already invited!'
                    return False
        except ObjectDoesNotExist:
            self.error = 'Error: No user exists with username "' + self.username + '"!'
            return False

        return True


class UploadFileForm(forms.Form):
    file = forms.FileField()
    title = forms.CharField(max_length=100, required=True)
    description = forms.CharField(widget=forms.Textarea, required=False)
    keywords = forms.CharField(max_length=255, required=False)


class ApproveUserRequestForm(forms.Form):
    username = forms.CharField()

events/views.py
from dateutil.relativedelta import relativedelta
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views import View
from django.views.generic import FormView
from django.conf import settings
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse

from organizations.models import Organization, OrganizationMember
from .forms import CreateEventForm, EventInviteUserForm, UploadFileForm
from .models import Event, EventParticipant, EventFile, Comment
from myaccount.models import User
import boto3
import mimetypes
from datetime import timedelta
from django.core.mail import send_mail
from myaccount.sms import * 
s3 = boto3.client(
    's3',
    aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
    aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
    region_name=settings.AWS_S3_REGION_NAME
)


class EventView(View):
    template_name = "events/view_event.html"

    def get(self, request, pk):
        event = get_event(pk)
        user = request.user

        # Handle event does not exist
        if event is None:
            return self.get_event_does_not_exist_view(request)
        # Handle anonymous user
        if not user.is_authenticated:
            return self.get_event_anonymous_view(request, event)
        
        # Get all files for the event
        files = EventFile.objects.filter(event=event)
        search_query = request.GET.get("search", "").strip()
        if search_query:
            files = files.filter(keywords__icontains=search_query)
            no_match = not files.exists()
        else:
            no_match = False

        is_participant = EventParticipant.objects.filter(event=event, user=user, status='Confirmed', approved=True).exists()
        # Find the next recurrence if the event is recurring
        next_recurrence = None
        if event.is_recurring:
            next_recurrence = Event.objects.filter(
                recurrence_id=event.recurrence_id,
                start_time__gt=event.start_time
            ).order_by('start_time').first()

        has_invitation = EventParticipant.objects.filter(event=event, user=user,status = "Invited", approved=False).exists()

        if user == event.creator or user.role == 2:  # admin or creator
            return self.get_event_owner_view(request, event, files, next_recurrence=next_recurrence, no_match=no_match)
        elif has_invitation:
            return self.get_user_not_in_event_view(request, event, optional_message="Your request is pending approval.")
        elif is_participant:
            return self.get_user_in_event_view(request, event, files, next_recurrence=next_recurrence, no_match=no_match)
        else:
            return self.get_user_not_in_event_view(request, event)

    def get_event_does_not_exist_view(self, request):
        return render(request, self.template_name)

    def get_event_anonymous_view(self, request, event):
        context = {
            "event": event, 'role': "anonymous"
        }
        return render(request, self.template_name, context)

    def get_user_not_in_event_view(self, request, event, optional_message=None):
        status = "none"
        approved = "none"
        event_participant = EventParticipant.objects.filter(event=event, user=request.user)
        if event_participant.exists():
            participant = event_participant.first()
            status = participant.status.lower()
            approved = participant.approved
        context = {
            "event": event, "role": "not-in-event", "status": status, "approved": approved
        }
        if optional_message:
            context["message"] = optional_message
        return render(request, self.template_name, context)

    def get_user_in_event_view(self, request, event, files, optional_message=None, next_recurrence=None, no_match=False):
        files = EventFile.objects.filter(event=event)
        participants = EventParticipant.objects.get(event=event, user=request.user)
        comments = Comment.objects.filter(event=event)
        if participants and participants.status == 'Confirmed' and participants.approved:
            can_upload_files = True
        else:
            can_upload_files = False

        invited_participants = []
        requested_participants = []
        event_participants = EventParticipant.objects.filter(event=event)
        for participant in event_participants:
            if participant.approved:
                invited_participants.append({
                    "username": participant.user.username,
                    "status": str(participant.status)}
                )
            elif not participant.approved and participant.status == "Denied":
                invited_participants.append({
                    "username": participant.user.username,
                    "status": str(participant.status)}
                )
            else:
                requested_participants.append({
                    "username": participant.user.username,
                    "status": str(participant.status)}
                )

        context = {
            "event": event, "event_files": files, "status": str(participants.status), "comments": comments, "role": "in-event",
            "message": optional_message, "can_upload_files": can_upload_files, "next_recurrence": next_recurrence, "no_match": no_match,
            "invited_participants": invited_participants, "requested_participants": requested_participants,
        }
        return render(request, self.template_name, context)

    def get_event_owner_view(self, request, event, files, optional_message=None, next_recurrence=None, no_match=False):
        event_participants = EventParticipant.objects.filter(event=event)
        comments = Comment.objects.filter(event=event)
        invited_participants = []
        requested_participants = []

        for participant in event_participants:
            if participant.approved:
                invited_participants.append({
                    "username": participant.user.username,
                    "status": str(participant.status)}
                )
            elif not participant.approved and participant.status == "Denied":
                invited_participants.append({
                    "username": participant.user.username,
                    "status": str(participant.status)}
                )
            else:
                requested_participants.append({
                    "username": participant.user.username,
                    "status": str(participant.status)}
                )

        role = "pma"
        if request.user.username == event.creator.username:
            role = "owner"

        context = {
            "event": event, "event_files": files, "invited_participants": invited_participants,
            "requested_participants": requested_participants, "comments": comments,
            "message": optional_message, "next_recurrence": next_recurrence, "role": role, "no_match": no_match
        }
        return render(request, self.template_name, context)

    def post(self, request, pk):
        event = get_event(pk)
        user = request.user

        # Handle event does not exist
        if event is None:
            return self.get_event_does_not_exist_view(request, pk)

        # Handle anonymous user
        if not user.is_authenticated:
            return self.get_event_anonymous_view(request, event)

        action = request.POST.get('action')
        delete_all = request.POST.get('delete_all') == 'true'

        if action == 'delete_event':
            event = get_object_or_404(Event, id=event.pk)
            # Check if the user is the creator or a PMA
            if request.user == event.creator or request.user.is_pma:
                if delete_all:
                    delete_all_future_occurrences(event)
                else:
                    event.delete()
                return JsonResponse({'success': True})

            return JsonResponse({'success': False}, status=403)

        # Handle user accept event
        if request.POST.get("form_type") == 'accept_event' and EventParticipant.objects.filter(event=event, user=user).exists():
            return self.post_accept_event(request, event)

        # Handle user deny event
        if request.POST.get("form_type") == 'deny_event' and EventParticipant.objects.filter(event=event, user=user).exists():
            return self.post_deny_accepting_event(request, event)

        # Handle Invite User Form
        if event.creator.username == user.username and request.POST.get("form_type") == 'invite_user':
            return self.post_invite_user_form(request, event)

        # Handle Upload Event Form
        if request.POST.get("form_type") == 'upload_file':
            is_creator = event.creator.username == user.username
            is_participant = EventParticipant.objects.filter(event=event, user=user, status="Confirmed", approved=True).exists()
            if is_creator or is_participant:
                return self.post_upload_file(request, event)

        # Handle Approve Event form
        if event.creator.username == user.username and request.POST.get("form_type") == 'approve_request':
            return self.post_approve_user_invite(request, event)

        # Handle Deny Event form
        if event.creator.username == user.username and request.POST.get("form_type") == 'deny_request':
            return self.post_deny_user_invite(request, event)

        # Handle Delete Invite Event form
        if event.creator.username == user.username and request.POST.get("form_type") == 'delete_invite':
            return self.post_delete_user_invite(request, event)

        # Handle Request Access Form
        if request.user != event.creator and request.POST.get("form_type") == 'request_access' \

events/templates/events/create_event.html
{% extends "myaccount/base.html" %}

<!--<script type=”text/javascript” src=”https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js”></script>-->
<!--<link href=”https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css” rel=”stylesheet”>-->
<!--<script src=”https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js”> </script>-->

<style>
    :root {
        --blue-theme: #E57200;
        --orange-color: #E57200;
    }
    [data-theme="dark"] {
        --blue-theme: #e9e9e9;
        --orange-color: #e9e9e9;
    }

    .blue-outline {
        border: 1px solid #e57200;
        outline: 1px solid #e57200;
    }
</style>

{% block title %}
Create event
{% endblock %}

{% block content %}
<div style="padding: 10%">

    <h1 class="display-1">Create your event:</h1>


    <form action="/events/submit/" method="post">
        {% csrf_token %}

        <!-- Title -->
        <div class="form-group row" style="padding-bottom: 10px">
            <label for="id_title" style="font-size: 1.5em">Title: </label>
            <input required id="id_title" class="form-control" style="border: 0 none; outline: 1px solid #0e3685" type="text" name="title" maxlength="200" value="">
        </div>

        <!-- Description -->
        <div class="form-group row" style="padding-bottom: 10px">
            <label for="id_description" style="font-size: 1.5em">Description: </label>
            <input required id="id_description" class="form-control" type="text" name="description" value="" style="min-height: 200px; border: 0 none; outline: 1px solid #0e3685">
        </div>


        <!-- Location -->
        <div class="form-group row" style="padding-bottom: 10px">
            <label for="id_location" style="font-size: 1.5em">Location: </label>
            <input required id="id_location" class="form-control" type="text" name="location" value="" style="border: 0 none; outline: 1px solid #0e3685">
        </div>


        <!-- Start time -->
        <div class="form-group row" style="padding-bottom: 10px">
            <label for="id_start_time" style="font-size: 1.5em">Start time:</label>
            <input required id="id_start_time" type="datetime-local" class="form-control" name="start_time" value="" style="border: 0 none; outline: 1px solid #0e3685">
        </div>

        <!-- End time -->
        <div class="form-group row" style="padding-bottom: 20px">
            <label for="id_end_time" style="font-size: 1.5em">End time:</label>
            <input required id="id_end_time" type="datetime-local" class="form-control" name="end_time" value="" style="border: 0 none; outline: 1px solid #0e3685">
        </div>

        <!-- Make Recurring -->
        <div class="form-group" style="padding-bottom: 10px">
            <label id ="repeat_checkbox_label"for="repeat_checkbox" style="font-size: 1.5em; padding-right: 20px">Will this event repeat?</label>
            <input type="checkbox" class="align-baseline" id="repeat_checkbox" name="repeat_checkbox" style="margin-left: 0;">
        </div>

        <!-- Only Appears If Recurrence Selected -->
        <!-- Recurrence Options -->
        <div class="form-group row" id="recurrence_options" style="display: none; padding-bottom: 10px;">
            <label for="id_is_recurring" style="font-size: 1.5em">How often will it repeat?</label>
            <select id="id_is_recurring" name="recurrence_frequency" class="form-control" style="border: 0 none; outline: 1px solid #0e3685">
                <option value="">Repeats:</option>
                <option value="daily">Daily</option>
                <option value="weekly">Weekly</option>
                <option value="monthly">Monthly</option>
                <option value="yearly">Yearly</option>
            </select>
        </div>
        <!-- End of Recurrence Date -->
        <div class="form-group row" id="recurrence_end_group" style="display: none; padding-bottom: 10px;">
            <label for="id_recurrence_end" style="font-size: 1.5em">When should it stop?</label>
            <input id="id_recurrence_end" type="datetime-local" class="form-control" name="recurrence_end" value="" style="border: 0 none; outline: 1px solid #0e3685">
        </div>

        <div class="container-fluid d-flex justify-content-center">
            <input type="submit" class="submit-button" value="Create" style="margin-bottom: 10px">
        </div>
        <div id="error-message" style="color: red; text-align: center; margin-top: 10px;"></div>

        <!-- End time error -->
        {% if form.errors %}
            <div class="alert alert-danger mt-3" role="alert">
                <strong>Error:</strong><br>
                {% for field in form %}
                    {% for error in field.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                {% endfor %}
            </div>
        {% endif %}
    </form>
</div>

<!-- Recurrence Script -->
<script>
    document.getElementById('repeat_checkbox').addEventListener('change', function() {
        const recurrenceOptions = document.getElementById('recurrence_options');
        const recurrenceEndGroup = document.getElementById('recurrence_end_group');
        if (this.checked) {
            recurrenceOptions.style.display = 'block';
            recurrenceEndGroup.style.display = 'block';
        } else {
            recurrenceOptions.style.display = 'none';
            recurrenceEndGroup.style.display = 'none';
            document.getElementById('recurrence_end_group').style.display = 'none';
        }
    });
</script>

{% endblock %}