events/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("create/", views.CreateEventView.as_view(), name="create_event"),
    path("submit/", views.submit_event, name="create_event"),
    path("<int:pk>/", views.EventView.as_view(), name="view_event"),
    path('<int:pk>/file/<int:file_id>/delete/', views.delete_event_file, name='delete_event_file'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('events/', include(("events.urls", 'events'), namespace="events")),
    path('organizations/', include('organizations.urls', namespace='organizations')),
    path('search/', include(("search.urls", 'search'), namespace="search")),
    path('upcoming/', include(("upcoming.urls", 'upcoming'), namespace="upcoming")),
    path('', include("myaccount.urls")),
    path('', include("pma.urls"))
]

organizations/urls.py
from django.urls import path
from . import views

app_name = 'organizations'

urlpatterns = [
    path('create/', views.create_organization, name='create_organization'),
    path('submit/', views.submit_organization, name='submit_organization'),
    
    path('<int:pk>/', views.OrganizationView.as_view(), name='view_organization'),  # View individual organization
    path('<int:pk>/edit/', views.edit_organization_view, name='edit_organization'),  # Edit individual organization
]

pma/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('pma/', views.pma_page, name='pma'),
    path('pma/edit_event/<int:user_id>/', views.edit_event, name='edit_event'),
    path('pma/delete_event/', views.delete_event, name='delete_event'),
]

search/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("organization/", views.OrganizationEventView.as_view(), name="organization-search"),
    path("", views.SearchEventView.as_view(), name="search")
]

search/models.py
from django.db import models

# Create your models here.

search/forms.py
from django import forms
from datetime import datetime


class SearchForm(forms.Form):
    title = forms.CharField(max_length=200, required=False, initial="")
    creator = forms.CharField(max_length=200, required=False, initial="")
    start_time = forms.DateTimeField(initial=None, required=False, widget=forms.DateTimeInput(format='%Y-%m-%dT%H:%M', attrs={'type': 'datetime-local', 'style': 'outline: none; border: none; width: 100%; background-color: transparent;'}))
    end_time = forms.DateTimeField(initial=None, required=False, widget=forms.DateTimeInput(format='%Y-%m-%dT%H:%M', attrs={'type': 'datetime-local', 'style': 'outline: none; border: none; width: 100%; background-color: transparent;'}))
    only_my_invited_events = forms.BooleanField(initial=False, required=False, widget=forms.CheckboxInput())
    only_my_accepted_events = forms.BooleanField(initial=False, required=False, widget=forms.CheckboxInput())
    only_my_friends_accepted = forms.BooleanField(initial=False, required=False)
    only_my_events = forms.BooleanField(initial=False, required=False)
    only_recurring_events = forms.BooleanField(initial=False, required=False)
    page_number = forms.IntegerField(initial=1, required=False)

search/views.py
import pytz
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django import forms
from django.views import View
from django.views.generic import FormView

from friend.models import Friend
from organizations.models import Organization
from search.forms import SearchForm
from events.models import Event, EventParticipant
from myaccount.models import User
from datetime import datetime, time, timedelta
from django.utils import timezone
from django.utils.dateparse import parse_datetime
from zoneinfo import ZoneInfo
from django.db.models import Q, OuterRef, Subquery

class OrganizationEventView(View):
    template_name = "search/organization_search.html"

    def get(self, request):
        self.redirect_to_home_if_not_authenticated(request)

        organizations = self.get_organizations(name="", creator_username="")

        return render(request, self.template_name, context= {
            "organizations": organizations
        })

    def post(self, request):
        self.redirect_to_home_if_not_authenticated(request)

        # Handle search for organization by name or creator username
        name = ""
        creator_username = ""
        if request.POST.get("name") is not None:
            name = request.POST.get("name")
        if request.POST.get("creator_username") is not None:
            creator_username = request.POST.get("creator_username")

        organizations = self.get_organizations(name=name, creator_username=creator_username)
        return render(request, self.template_name, context= {
            "organizations": organizations, "name": name, "creator_username": creator_username
        })

    def redirect_to_home_if_not_authenticated(self, request):
        if not request.user.is_authenticated:
            return redirect('/')

    def get_organizations(self, name, creator_username):
        organizations = Organization.objects

        if name is not None:
            organizations = organizations.filter(name__icontains=name)

        if creator_username is not None:
            organizations = organizations.filter(creator__username__icontains=creator_username)

        # Format for template
        organizations_formatted = []
        for organization in organizations:
            organizations_formatted.append({
                'name': organization.name,
                'pk': organization.pk,
                'creator': organization.creator
            })
        return organizations_formatted

class SearchEventView(View):
    template_name = "search/event_search.html"

    def get(self, request):
        initial = {'start_time': datetime.now(), 'page_number': 1}
        events = get_all_events_after_today()
        return self.get_search_view(
            request,
            SearchForm(initial=initial),
            events,
            "Upcoming events:"
        )

    def get_search_view(self, request, form, events, search_title):
        # Filter by start time
        events = events.order_by('start_time')

        # Get page number
        page_number = form.initial.get('page_number', 1)

        # Get events within the first 10 entries and get the total number of events that matched the criteria
        events_in_range, total_event_count = only_get_events_on_page(events, page_number)

        # Convert the events into event information for the template
        events_information = get_events_information_from_events(events_in_range, request.user)

        # Calculate the highest possible page to display given the number of events
        highest_page = total_event_count // 10 + (0 if ((total_event_count % 10) == 0) else 1)
        if highest_page == 0:
            highest_page = 1
        if page_number > highest_page:
            form.initial['page_number'] = 1

        return render(request, self.template_name, {
            "form": form, "search_title": search_title, "events": events_information,
            "total_event_count": total_event_count, "highest_page": highest_page
        })

    def post(self, request):
        form = SearchForm(request.POST)
        if form.is_valid():
            # Handle next page button pressed
            page_number = int(form.cleaned_data['page_number'])
            if 'next' in request.POST:
                page_number = page_number + 1
            # Handle previous page button pressed
            elif 'prev' in request.POST:
                page_number = page_number - 1
            # Handle search button pressed
            elif 'search' in request.POST:
                page_number = 1

            # Clean form data
            cleaned_data = {
                'title': form.cleaned_data['title'],
                'creator': form.cleaned_data['creator'],
                'start_time': form.cleaned_data['start_time'],
                'end_time': form.cleaned_data['end_time'],
                'only_my_invited_events': form.cleaned_data['only_my_invited_events'],
                'only_my_accepted_events': form.cleaned_data['only_my_accepted_events'],
                'only_my_friends_accepted': form.cleaned_data['only_my_friends_accepted'],
                'only_my_events': form.cleaned_data['only_my_events'],
                'only_recurring_events': form.cleaned_data['only_recurring_events'],
                'page_number': page_number,
            }

            # Create new form using old form data and search with this new form
            events = get_searched_events_from_form(form=form, user=request.user)
            form = SearchForm(initial=cleaned_data)
            return self.get_search_view(request, form, events, "Search Results:")
        else:
            # Something went wrong, which shouldn't happen, but display error just in case.
            print("Error in Search form:")
            print(form.errors)
            # Return to initial search page as error occurred
            return self.get(request)


def get_searched_events_from_form(form, user):
    query_set = Event.objects.all()

    # Filter by text data
    query_set = filter_by_text_forms(form, query_set)

    # Filter by check list data
    query_set = filter_by_boolean_forms(form, user, query_set)

    return query_set


def filter_by_boolean_forms(form, user, query_set):
    # Filter only my events
    cleaned_only_my_events = form.cleaned_data['only_my_events']
    if cleaned_only_my_events is not None and cleaned_only_my_events is True and user.is_authenticated:
        query_set = query_set.filter(creator=user)

    # Filter recurring events
    cleaned_only_recurring_events = form.cleaned_data['only_recurring_events']
    if cleaned_only_recurring_events is not None and cleaned_only_recurring_events is True and user.is_authenticated:
        query_set = query_set.filter(is_recurring=True)

    # Filter invited events
    cleaned_only_my_invited_events = form.cleaned_data['only_my_invited_events']
    if cleaned_only_my_invited_events is not None and cleaned_only_my_invited_events is True and user.is_authenticated:
        # Filter by only invited events
        user_invited_events = (EventParticipant.objects.filter(user=user)
                               .filter(approved=True)
                               .filter(status='Invited')
                               .filter(event__in=query_set))
        # Construct list of PK to filter by invited events
        participants = []
        for event_participants in user_invited_events:
            participants.append(event_participants.event.pk)
        # Filter by PK
        query_set = query_set.filter(pk__in=participants)

    # Filter accepted events
    cleaned_only_my_accepted_events = form.cleaned_data['only_my_accepted_events']
    if cleaned_only_my_accepted_events is not None and cleaned_only_my_accepted_events is True and user.is_authenticated:
        # Filter by only accepted events
        user_accepted_events = (EventParticipant.objects
                                .filter(user=user)
                                .filter(approved=True)
                                .filter(status='Confirmed')
                                .filter(event__in=query_set))
        # Construct list of PK to filter by accepted events
        participants = []
        for event_participants in user_accepted_events:
            participants.append(event_participants.event.pk)
        # Filter by PK
        query_set = query_set.filter(pk__in=participants)

    # Filter friends accepted events
    cleaned_only_my_friends_accepted = form.cleaned_data['only_my_friends_accepted']
    if cleaned_only_my_friends_accepted is not None and cleaned_only_my_friends_accepted is True and user.is_authenticated:
        # Get query set of accepted friends
        friends_query_set = (Friend.objects.filter(from_user=user).filter(status=Friend.STATUS_ACCEPTED))

        # Get friends pk
        friends_pk = []
        for friend in friends_query_set:
            friends_pk.append(friend.to_user.pk)

        # Get list of event participants that include friends
        participants = (EventParticipant.objects.filter(status="Confirmed")
                                                .filter(event__in=query_set)
                                                .filter(user__in=friends_pk))

        # Construct list of PK to filter by accepted events
        participants_events_pk = []
        for participant in participants:
            participants_events_pk.append(participant.event.pk)

        # Filter list of events if creator is a friend or if is confirmed event participant
        query_set = query_set.filter(Q(creator__pk__in=friends_pk) | Q(pk__in=participants_events_pk))

    return query_set


def filter_by_text_forms(form, query_set):
    # Filter Start time
    cleaned_start_time = form.cleaned_data['start_time']
    if cleaned_start_time is not None and cleaned_start_time != "":

search/templates/search/event_search.html
{% extends "myaccount/base.html" %}

{% block title %}
Search for an event
{% endblock %}

{% block content %}

<style>
    :root {
        --blue-color: #232D4B;
        --orange-color: #E57200;
    }
    [data-theme="dark"] {
        --blue-color: #e9e9e9;
        --orange-color: #e9e9e9;
    }

    .blue-class {
        color: var(--blue-color);
    }

    .blue-line {
        border-bottom: 2px solid #0e3685
    }

    .submit-button {
        background-color: #E57200;
        color: #ffffff;
        border: none;
        padding: 10px 20px;
        font-size: 16px;
        border-radius: 4px;
    }

    .submit-button:hover {
        background-color: #d96e00;
        border: 1px solid #0e3685;
    }

    .view-event-button {
        background-color: #E57200;
        color: #ffffff;
        border: none;
        border-radius: 4px;
        padding: 10px 20px;
    }

    .title-link-hover:hover {
        color: #E57200;
        font-weight: bolder;
    }


    .info-search-border {
        border-radius: 0;
        border: 2px solid var(--blue-color)
    }

    .info-search-element-border {
        border: 0 none;
    }
    .info-search-row-element {
        border: 0 none;
    }
    .info-search-row {
        border-left: 1px solid #cccccc;
        border-bottom: 1px solid #cccccc;
        border-right: 1px solid #cccccc;
        border-top: 0 none;
        border-radius: 0;
    }
    .form-control-by-theme {
        border: 0;
        outline: 1px solid var(--blue-color);
        background-color: transparent;
    }
    .checkbox-by-theme {
        background-color: transparent;
    }
</style>

<div style="padding: 50px"></div>

<div style="padding: 2%">

    <h1 class="display-5 blue-class" style="font-weight: bold;">Event Search:</h1>
    <hr class="blue-line" style="margin-bottom: 30px">

    <form action="/search/" method="post">
        {% csrf_token %}
        <!-- Top row -->
        <div class="row blue-class align-items-center">
            <div class="col-3" style="min-height: 50px">
                <label for="id_title" style="font-weight: bold">Title:</label>
                <input id="id_title" type="text" class="form-control form-control-by-theme" name="title" value='{{ form.title.value|default_if_none:"" }}' placeholder="-">
            </div>
            <div class="col-3">
                <label for="id_creator" style="font-weight: bold">Creator: </label>
                <input id="id_creator" type="text" class="form-control form-control-by-theme" name="creator" value='{{ form.creator.value|default_if_none:"" }}' placeholder="-">
            </div>
            <div class="col-3">
                <label for="id_start_time" style="font-weight: bold">From time: </label>
                <div id="id_start_time" name="start_time" class="form-control form-control-by-theme checkbox-by-theme">
                    <div style="border: none; outline: none; background-color: transparent">
                        {{ form.start_time }}
                    </div>
                </div>
            </div>
            <div class="col-3">
                <label for="id_end_time" style="font-weight: bold">To time: </label>
                <div id="id_end_time" name="end_time" class="form-control form-control-by-theme checkbox-by-theme">
                    {{ form.end_time }}
                </div>
            </div>
        </div>

        <div class="mt-1"> </div>

        <!-- Bottom row -->
        <div class="list-group list-group-horizontal blue-class align-items-center">
            {% if user.is_authenticated and user.role != 2 %}
                <div class="form-control checkbox-by-theme blue-class" style="border-width: 0; max-width: 17%;">
                    <label for="id_only_my_invited_events" style="font-weight: bold">
                        <div id="id_only_my_invited_events" name="only_my_invited_events">
                            {{ form.only_my_invited_events }}
                            Invited Events
                        </div>
                    </label>
                </div>
                <div class="form-control checkbox-by-theme blue-class" style="border-width: 0; max-width: 17%;">
                    <label for="id_only_my_accepted_events" style="font-weight: bold">
                        <div id="id_only_my_accepted_events" name="only_my_accepted_events">
                            {{ form.only_my_accepted_events }}
                            Accepted Events
                        </div>
                    </label>
                </div>
                <div class="form-control checkbox-by-theme blue-class" style="border-width: 0; max-width: 17%;">
                    <label for="id_only_my_friends_accepted" style="font-weight: bold">
                        <div id="id_only_my_friends_accepted" name="only_my_friends_accepted">
                            {{ form.only_my_friends_accepted }}
                            Friends Events
                        </div>
                    </label>
                </div>
                <div class="form-control checkbox-by-theme blue-class" style="border-width: 0; max-width: 17%;">
                    <label for="id_only_my_events" style="font-weight: bold">
                        <div id="id_only_my_events" name="id_only_my_events">
                            {{ form.only_my_events }}
                            Your Events
                        </div>
                    </label>
                </div>
                <div class="form-control checkbox-by-theme blue-class" style="border-width: 0; max-width: 17%;">
                    <label for="id_only_recurring_events" style="font-weight: bold">
                        <div id="id_only_recurring_events" name="only_recurring_events">
                            {{ form.only_recurring_events }}
                            Recurring Events
                        </div>
                    </label>
                </div>
            {% else %}
                {% if user.role != 2 %}
                    <li class="list-group-item" style="border-width: 0;">
                        <p>You are logged in anonymously, so you have limited search information! Log-in to see more!</p>
                    </li>
                {% endif %}
            {% endif %}
            <li class="list-group-item flex-fill" style="border-width: 0;">
                <button type="submit" class="submit-button pull-right" name="search" style="float:right; margin: 9px">Search</button>
            </li>
        </div>
        <hr class="blue-line">

        <!-- Search Results -->
        <h1 class="display-6" style="font-weight: bold;">{{ search_title }}</h1>
        <div class="blue-class" style="margin-left: 2%; margin-right: 2%; margin-bottom: 2%;">
            <i>Showing {{ events|length }} out of {{ total_event_count }} events</i>
            <div style="margin-bottom: 1%"></div>
            <div class="list-group list-group-horizontal blue-class align-items-center info-search-border" style="font-weight: bold;">
                {% if user.is_authenticated %}
                    <div class="col-2 list-group-item info-search-element-border blue-class">
                        Title:
                    </div>
                    <div class="col-3 list-group-item info-search-element-border blue-class">
                        Description:
                    </div>
                    <div class="col-2 list-group-item info-search-element-border blue-class">
                        Creator:
                    </div>
                    <div class="col-2 list-group-item info-search-element-border blue-class">
                        Start time:
                    </div>
                    <div class="col-2 list-group-item info-search-element-border blue-class">
                        End time:
                    </div>
                    <div class="col-1 list-group-item info-search-element-border text-center blue-class">
                        Status:
                    </div>
                {% else %}
                    <div class="col-3 list-group-item info-search-element-border blue-class">
                        Title:
                    </div>
                    <div class="col-3 list-group-item info-search-element-border text center blue-class">
                        Description:
                    </div>
                    <div class="col-2 list-group-item info-search-element-border blue-class">
                        Creator:
                    </div>
                    <div class="col-2 list-group-item info-search-element-border blue-class">
                        Start time:
                    </div>
                    <div class="col-2 list-group-item info-search-element-border blue-class">
                        End time:
                    </div>
                {% endif %}
            </div>
            {% if events %}
                {% for event in events %}
                    <div class="list-group list-group-horizontal blue-class align-items-center info-search-row">
                        {% if user.is_authenticated %}
                            <div class="col-2 list-group-item info-search-row-element">
                                <a href="{% url 'events:view_event' event.pk %}" class="blue-class title-link-hover" style="font-weight: bold; text-decoration: none">
                                    {{ event.title }}
                                </a>
                            </div>
                            <div class="col-3 list-group-item info-search-row-element blue-class">
                                {{ event.description }}
                            </div>
                            <div class="col-2 list-group-item info-search-row-element blue-class">
                                <i>{{ event.creator }}</i>
                            </div>
                            <div class="col-2 list-group-item info-search-row-element blue-class">
                                {{ event.start_time }}
                            </div>
                            <div class="col-2 list-group-item info-search-row-element blue-class">
                                {{ event.end_time }}
                            </div>
                            <div class="col-1 list-group-item info-search-row-element text-center blue-class">
                                {{ event.status }}
                            </div>
                        {% else %}
                            <div class="col-3 list-group-item info-search-row-element">
                                <a href="{% url 'events:view_event' event.pk %}" class="blue-class title-link-hover" style="font-weight: bold; text-decoration: none">
                                    {{ event.title }}
                                </a>
                            </div>
                            <div class="col-3 list-group-item info-search-row-element blue-class">
                                {{ event.description }}
                            </div>
                            <div class="col-2 list-group-item info-search-row-element blue-class">
                                <i>{{ event.creator }}</i>
                            </div>
                            <div class="col-2 list-group-item info-search-row-element blue-class">
                                {{ event.start_time }}
                            </div>
                            <div class="col-2 list-group-item info-search-row-element blue-class">
                                {{ event.end_time }}
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}
            {% else %}
                <p style="margin:5%">
                    <b>Uh-oh!</b>
                    No events were found that matched your search criteria!
                </p>
            {% endif %}

            <label hidden for="id_page_number">page_number</label>
            <input hidden id="id_page_number" type="number" class="align-baseline" name="page_number" value='{{ form.page_number.value|default_if_none:1 }}' style="margin-left: 0;">

            <div class="d-flex justify-content-end align-items-center" style="margin: 10px;">
                {% if events %}
                    <i class="align-text-middle">
                        Showing page {{ form.page_number.value|default_if_none:1 }} of {{ highest_page }}
                    </i>
                {% endif %}
                {% if form.page_number.value != 1 %}
                    <button type="submit" class="submit-button" name="prev" style="margin-left: 20px; padding: 5px 15px">
                        Previous Page
                    </button>
                {% endif %}
                {% if form.page_number.value != highest_page %}
                    <button type="submit" class="submit-button" name="next" style="margin-left: 20px; padding: 5px 15px">
                        Next Page
                    </button>
                {% endif %}
            </div>
        </div>
        <hr class="blue-line" style="margin-bottom: 100px">
    </form>
</div>

{% endblock %}

search/templates/search/organization_search.html
{% extends "myaccount/base.html" %}

{% block title %}
Search for an organization
{% endblock %}

{% block content %}

<style>
:root {
    --blue-color: #232D4B;
    --orange-color: #E57200;
}
[data-theme="dark"] {
    --blue-color: #e9e9e9;
    --orange-color: #e9e9e9;
}

.blue-class {
color: var(--blue-color);
}

.blue-line {
    border-bottom: 2px solid #0e3685
}

.submit-button {
    background-color: #E57200;
        color: #ffffff;
border: none;
padding: 10px 20px;
font-size: 16px;
border-radius: 4px;
}

.submit-button:hover {
    background-color: #d96e00;
        border: 1px solid #0e3685;
}

.view-event-button {
    background-color: #E57200;
        color: #ffffff;
border: none;
border-radius: 4px;
padding: 10px 20px;
}

.title-link-hover:hover {
    color: #E57200;
    font-weight: bolder;
}


.info-search-border {
    border-radius: 0;
border: 2px solid var(--blue-color)
}

.info-search-element-border {
    border: 0 none;
}
.info-search-row-element {
    border: 0 none;
}
.info-search-row {
    border-left: 1px solid #cccccc;
    border-bottom: 1px solid #cccccc;
    border-right: 1px solid #cccccc;
    border-top: 0 none;
border-radius: 0;
}
.form-control-by-theme {
    border: 0;
    outline: 1px solid var(--blue-color);
    background-color: transparent;
}
.search-icon {
    width: 50px;
    height: 50px;
    background-color: white;
    border: 1px solid #232D4B;
}
.search-icon:hover {
    width: 50px;
    height: 50px;
    background-color: #232D4B;
}
</style>

<div style="padding: 50px"></div>

<div style="padding: 2%">
    <h1 class="display-5 blue-class" style="font-weight: bold;">Organization Search:</h1>
    <hr class="blue-line" style="margin-bottom: 30px">
    <form action="/search/organization/" method="post">
        {% csrf_token %}
        <div class="row blue-class align-items-center">
            <div class="col-4" style="min-height: 50px">
                <label for="id_name" style="font-weight: bold">Name:</label>
                <input id="id_name" type="text" class="form-control form-control-by-theme" name="name" value='{{ name|default_if_none:"" }}' placeholder="-">
            </div>
            <div class="col-4">
                <label for="id_creator_username" style="font-weight: bold">Creator: </label>
                <input id="id_creator_username" type="text" class="form-control form-control-by-theme" name="creator_username" value='{{ creator_username|default_if_none:"" }}' placeholder="-">
            </div>
            <div class="col-3"></div>
            <div class="col-1">
                <button class="btn d-flex align-items-center justify-content-center search-icon">
                    {% load static %}
                    <img src="{% static 'admin/img/search.svg' %}" alt="Search" />
                </button>
            </div>
        </div>

        <div class="fluid-container" style="margin-top: 30px; border-left: 1px solid var(--blue-color); border-right: 1px solid var(--blue-color)">
            <div class="list-group list-group-horizontal blue-class align-items-center" style="font-weight: bold; min-height: 50px; color: white; background-color: #232D4B; border-radius: 0">
                <div class="col-8 align-items-center text-center" style="border-right: 1px solid white">
                    Organization name:
                </div>
                <div class="col-4 align-items-center text-center">
                    Creator username:
                </div>
            </div>
            {% if organizations %}
                {% for organization in organizations %}
                    <div class="list-group list-group-horizontal align-items-center" style="min-height: 40px; color: var(--blue-color); background-color: var(--background-color); border-radius: 0; border-bottom: 1px solid #232D4B">
                        <div class="col-8 align-items-center text-center">
                            <a href="{% url 'organizations:view_organization' organization.pk %}" class="title-link-hover" style="text-decoration: none; color: var(--blue-color);">
                                {{ organization.name }}
                            </a>
                        </div>
                        <div class="col-4 align-items-center text-center">
                            {{ organization.creator.username }}
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="list-group list-group-horizontal blue-class align-items-center" style="min-height: 40px; padding: 30px; border-radius: 0; border-bottom: 1px solid #232D4B">
                    No organizations were found!
                </div>
            {% endif %}
        </div>
    </form>
    <hr class="blue-line" style="margin-bottom: 50px; margin-top: 50px">
</div>

{% endblock %}