events/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("create/", views.CreateEventView.as_view(), name="create_event"),
    path("submit/", views.submit_event, name="create_event"),
    path("<int:pk>/", views.EventView.as_view(), name="view_event"),
    path('<int:pk>/file/<int:file_id>/delete/', views.delete_event_file, name='delete_event_file'),
]

myaccount/urls.py
from django.urls import path, include

from . import views
from friend import views as friend_views
from pma import views as pma_views

urlpatterns = [
    path("myaccount/", views.my_account, name="myaccount"),
    path('', views.landing_page, name='landing_page'),
    path('auth/', include('social_django.urls', namespace='social')),
    path('auth/redirect/',views.redirect_after_login, name='auth-redirect'),
    path('account_setup/', views.account_setup, name='account_setup'),
    path('logout', views.handle_logout, name="logout"),
    path('friends/', friend_views.friends_page, name="friends"),
    path('pma/', pma_views.pma_page, name="pma"),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('update-profile-info/', views.update_profile_info, name='update_profile_info'),
    path('notification-settings/', views.update_notification_settings, name='notification_settings'),
    path('verify-phone-number/', views.verify_phone_number, name ='verify_phone_number'),
    path('delete-account/', views.delete_account, name='delete_account'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('events/', include(("events.urls", 'events'), namespace="events")),
    path('organizations/', include('organizations.urls', namespace='organizations')),
    path('search/', include(("search.urls", 'search'), namespace="search")),
    path('upcoming/', include(("upcoming.urls", 'upcoming'), namespace="upcoming")),
    path('', include("myaccount.urls")),
    path('', include("pma.urls"))
]

pma/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('pma/', views.pma_page, name='pma'),
    path('pma/edit_event/<int:user_id>/', views.edit_event, name='edit_event'),
    path('pma/delete_event/', views.delete_event, name='delete_event'),
]

myaccount/forms.py
from django import forms
from .models import User
import re
class ProfilePictureUpdateForm(forms.Form):
    file = forms.FileField()
    
class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = User  
        fields = ['username', 'phone_number']
    
    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        phone_number = cleaned_data.get("phone_number")
        self.check_username(username)
        self.check_phone_number(phone_number)
        return cleaned_data
    
    def check_username(self, username):
        if not username:
            self.add_error("username", "Username cannot be empty!")
            return
        if username is None or len(username) < 6:
            self.add_error("username", "Username must be greater than 6 characters!")
            return
        if not re.match(r'^[a-zA-Z0-9]+$', username):
            self.add_error("username", "Username can only contain letters and numbers, no spaces or special characters!")
            return
        if User.objects.filter(username=username).exclude(pk=self.instance.pk).exists():
            self.add_error("username", "This username is already in use!")
            return

    def check_phone_number(self, pn):
        if pn:
            if len(pn) != 10:
                self.add_error("phone_number", "Mobile number must be 10 digits long!")
                return
            if User.objects.filter(phone_number=pn).exclude(pk=self.instance.pk).exists():
                self.add_error("phone_number", "This mobile number is already in use by another account!")
                return
            pattern = r'^\d{10}$'
            if not re.match(pattern, pn):
                self.add_error("phone_number", "Mobile number must contain only digits!")
                return

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
        return user

myaccount/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from .forms import *
from .models import *
from django.contrib.auth import logout
from events.models import *
import boto3
from django.utils import timezone
import os
import mimetypes
from .sms import *
# Create your views here.


def verify_phone_number(request):
    if not request.user.is_authenticated:
        return render(request, "myaccount/landingpage.html")
    if request.method == "POST":
        otp1 = request.POST.get("otp1")
        otp2 = request.POST.get("otp2")
        otp3 = request.POST.get("otp3")
        otp4 = request.POST.get("otp4")

        entered_code = f"{otp1}{otp2}{otp3}{otp4}"
        try:
            verification_record = VerifyPhoneNumber.objects.get(user=request.user)
            expected_code = verification_record.verification_code
            if entered_code == str(expected_code):
                verification_record.verified_number = True
                verification_record.save()
                return redirect("myaccount")
            else:
                return render(request, "myaccount/phone_verification", {"verify_error" : "Entered code did not match up! Please resend code or try again!"})
        except VerifyPhoneNumber.DoesNotExist:
            print("verify record doesnt exist")
    else: #sms verifying
        verified_num = VerifyPhoneNumber.objects.filter(user=request.user).first()
        if verified_num is not None:
            verified_num.verification_code = generate_verification_code()
            verified_num.save()
            send_verification_code(request.user.phone_number, verified_num.verification_code)
            return render(request, "myaccount/phone_verification.html")
        else:
             return render(
                request,
                "myaccount/phone_verification.html",
                {"verify_error": "No verification record found. Please contact support."},
            )
def update_notification_settings(request):
    if not request.user.is_authenticated:
        return render(request, 'myaccount/notification_setup.html')
    if request.user.phone_number is None:
        return render(request, 'myaccount/notification_setup.html', {"notif_error": True})
    verified_num = VerifyPhoneNumber.objects.filter(user=request.user).first()
    if verified_num is None:
        return render(request,'myaccount',{"notif_error": True})
    if request.method == "POST":
        email_notif = request.POST.get("email_notifications") == "on"
        sms_notif = request.POST.get("sms_notifications") == "on"
        preferences, created = NotificationPreference.objects.get_or_create(user=request.user)
        preferences.email_notifications = email_notif
        preferences.sms_notifications = sms_notif
        preferences.save()
        
    preferences, created = NotificationPreference.objects.get_or_create(user=request.user)
    return render(request, 'myaccount/notification_setup.html', {
        'preferences': preferences
    })

def my_account(request):
    user = request.user
    if not user.is_authenticated:
        return render(request, 'myaccount/myaccount.html')
    profile_picture = ProfilePicture.objects.filter(user=user).first()
    verified_num = VerifyPhoneNumber.objects.filter(user=user).first()
    context = {"profile_picture": profile_picture , "verified": verified_num}
    return render(request, 'myaccount/myaccount.html', context)


def update_profile_info(request):
    user = request.user
    if not user.is_authenticated:
        return render(request, 'myaccount/myaccount.html')
    if request.method == "POST": #update form
        form = UpdateProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            user.username = username
            user.save()
            verify_phone,created = VerifyPhoneNumber.objects.get_or_create(user = user)
            profile_picture = ProfilePicture.objects.filter(user=user).first()
            current_phone = request.user.phone_number
            new_phone_number = form.cleaned_data.get("phone_number")
            print(f"{verify_phone.verified_number}")
            if current_phone != new_phone_number:
                generate_code = generate_verification_code()
                verify_phone.verification_code = generate_code
                verify_phone.verified_number = False
                verify_phone.save()
                form.save()
            else:
                verify_phone.verified_number = verify_phone.verified_number
                verify_phone.save()
            return render(request, 'myaccount/myaccount.html', {"profile_picture": profile_picture, "verified": verify_phone})
        else:
            print("invalid form")
    else: #redirect with context to account with update profile view
        form = UpdateProfileForm(instance=request.user)
    profile_picture = ProfilePicture.objects.filter(user=user).first()
    context = {"update_profile_info": True, "form": form, "profile_picture" : profile_picture}
    return render(request, 'myaccount/myaccount.html', context)


def update_profile(request):
    form = ProfilePictureUpdateForm(request.POST, request.FILES)
    if 'file' not in request.FILES:
        return redirect('myaccount')
    if form.is_valid and 'file' in request.FILES:
        uploaded_file = request.FILES['file']
        s3_path = f'profile/{request.user.id}/{uploaded_file.name}'
        content_type, _ = mimetypes.guess_type(uploaded_file.name)
        allowed_mime_types = ['image/png', 'image/jpeg']
        allowed_extensions = ['.png', '.jpg', '.jpeg', '.jfif']
        file_extension = os.path.splitext(uploaded_file.name)[-1].lower()
        if content_type not in allowed_mime_types or file_extension not in allowed_extensions:
            context = {'file_error_msg': "Error: Only PNG, JPG, JPEG, and JFIF files are allowed!"}
            return render(request, 'myaccount/myaccount.html', context)
        try:
            s3 = boto3.client(
            's3',
            aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
            aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
            region_name=settings.AWS_S3_REGION_NAME
            )
            try:
                profile_file = ProfilePicture.objects.get(user=request.user)
                old_s3_path = profile_file.profile_picture
                s3.delete_object(
                    Bucket=settings.AWS_STORAGE_BUCKET_NAME,
                    Key=str(old_s3_path),
                )
            except ProfilePicture.DoesNotExist:
                profile_file = ProfilePicture(user=request.user)

            s3.upload_fileobj(
                uploaded_file,
                settings.AWS_STORAGE_BUCKET_NAME,
                s3_path,
                ExtraArgs={
                    'ContentType': content_type or 'application/octet-stream',
                    'ContentDisposition': 'inline'
                }
            )
            profile_file.profile_picture = s3_path
            profile_file.save()
            context = {"profile_picture": profile_file}
            return render(request, "myaccount/myaccount.html", context = context)

        except Exception as e:
            print(f"Failed to upload file to S3: {e}")

def landing_page(request):
    def get_upcoming_events(val):
        events_info = []
        if val == 2:
            event_participants = EventParticipant.objects.filter(user=request.user)
        else:
            event_participants = EventParticipant.objects.filter(user=request.user, event__start_time__gte=timezone.now()).order_by('event__start_time')[:5]
        for event_participant in event_participants:
            status = event_participant.status
            event_title = event_participant.event.title
            event_pk = event_participant.event.pk
            events_info.append({
                "status": status,
                "title": event_title,
                "event_pk": event_pk,
            })
        return events_info
    def get_my_events(val):
        my_events_list= []
        if val == 1:
            my_events = Event.objects.filter(creator = request.user)
        else:
            my_events = Event.objects.filter(creator = request.user)[:5]
        for event in my_events:
            title = event.title
            location = event.location
            start_time = event.start_time
            end_time = event.end_time
            event_pk = event.pk
            my_events_list.append({"title": title, 
                                   "location": location, 
                                   "start_time": start_time, 
                                   "end_time": end_time,
                                   'pk': event_pk
                                   })
        return my_events_list

    if request.user.is_authenticated:
        key_value = request.GET.get('key')
        if key_value is None:
            key_value = 0
        else:
            key_value = int(key_value)
        upcoming_events = get_upcoming_events(key_value)
        my_events = get_my_events(key_value)
        context = {"upcoming_events": upcoming_events, "my_events": my_events}
        return render(request, 'myaccount/landingpage.html', context)

    return render(request, 'myaccount/landingpage.html')

@login_required
def user_info(request):
    user = request.user
    user_data = {
        'email': user.email,
        'first_name': user.first_name,
        'last_name': user.last_name,
    }
    return JsonResponse(user_data)
@login_required
def redirect_after_login(request):
    user = request.user
    user.refresh_from_db()
    if user.username is None or int(user.role) == 0:  
        return redirect('account_setup') 
    return redirect('myaccount')  
@login_required

def account_setup(request):
    user = request.user

myaccount/templates/myaccount/account_setup.html
{% extends "myaccount/base.html" %}

{% block title %}
    Poll Results
{% endblock %}

{% block content %}

<style>
    .profile-form-container {
        max-width: 600px;
        margin: 50px auto; 
        padding: 40px;
        }
</style>

<div class="container mt-5">
    <div class="profile-form-container">
        <h3 class="text-center" style="color: var(--blue-color)">Enter Your Information</h3>
        <form method="post" action="">
            {% csrf_token %}
            <div class="mb-3">
                <label for="first_name">First Name</label>
                <input type="text" class="form-control" id="first_name" name="first_name" value="{{ user.first_name }}">
            </div>
            <div class="mb-3">
                <label for="last_name">Last Name</label>
                <input type="text" class="form-control" id="last_name" name="last_name" value="{{ user.last_name }}">
            </div>
            <div class="mb-3">
                <label for="username">Username</label>
                <input type="text" class="form-control" id="username" name="username" placeholder="Enter your username">
                {% if form.username.errors %}
                    <div class="error-message">{{ form.username.errors.0 }}</div>
                {% endif %}
            </div>
            <div class="mb-3">
                <label for="phone_number">Mobile Number</label>
                <input type="text" class="form-control" id="phone_number" name="phone_number" placeholder="Enter your Mobile Number">
                {% if form.phone_number.errors %}
                    <div class="error-message">{{ form.phone_number.errors.0 }}</div>
                {% endif %}
            </div>
            <div class="mb-3">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" name="email" value="{{ user.email }}">
            </div>
            <div class="text-center mt-4">
                <button type="submit" class="update-profile-btn">Save</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

myaccount/templates/myaccount/base.html
<!--# Title: Navbar-->
<!--#-->
<!--# Date Accessed: October 2, 2024-->
<!--#-->
<!--# URL: https://getbootstrap.com/docs/5.3/components/navbar/-->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cavalier Connect</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/event_styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/myaccount.css' %}">
    <link rel="stylesheet" href="{% static 'css/pma.css' %}">
    <link rel="stylesheet" href="{% static 'css/landing.css' %}">
    <script
            src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous">
    </script>

    <style>
        .navbar {
            position: fixed;
            top: 0;
            width: 100%;
            z-index: 1000;
        }
        main {
            margin-top: 10px;
            margin-bottom: -40px;
        }
        .footer {
            position: relative;
            width: 100%;
            padding: 1rem;
            text-align: center;
            border-top: 1px solid #e9ecef;
            margin-top: auto;
        }
        .custom-drop-down-menu {
            background-color: transparent;
            border: none;
        }
        .custom-drop-down-element {
            color: #0e3685;
        }
        .btn-action {
            background-color: #E57200;
            color: var(--text-color);
            padding: 10px;
            border-radius: 4px;
        }
        .btn-action:hover {
            background-color: #c06102;
            color: var(--text-color);
            box-shadow: 0 4px 8px rgba(var(--background-rgb), 0.5);
        }
        .log-button {
            color: white;
            background-color: #e57200;
            text-decoration: None;
            border: 1px solid #e57200;
            border-radius: 5px;
            padding: 5px 10px;
        }
        .log-button:hover {
            color: #e57200;
            background-color: white;
            text-decoration: None;
            border: 1px solid #e57200;
            border-radius: 5px;
            padding: 5px 10px;
        }
    </style>
    

</head>

<body>

    <nav class="navbar navbar-expand-md navbar-pma">
        <div class="container-fluid">
            <a class="navbar-brand fw-bold" href="/"><span style="color:orange">Cavalier</span> Connect</a>
            {% if user.is_authenticated and user.role == 2 %}
                <a class="navbar-brand ml-1" href="/">[PMA]</a>
            {% endif %}
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse align-items-center" id="navbarNav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 align-items-center text-center">

                    <!-- My account drop down menu-->
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <button class="btn btn-primary dropdown-toggle custom-drop-down-menu" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                                My Account
                            </button>

                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                {% if user.role == 1 %}
                                    <li><a class="dropdown-item custom-drop-down-element" href="/myaccount">Profile</a></li>
                                    <li><a class="dropdown-item custom-drop-down-element" href="/friends">Friends</a></li>
                                {% endif %}
                                {% if user.role == 2 %}
                                    <li><a class="dropdown-item custom-drop-down-element" href="/pma">PMA Dashboard</a></li>
                                {% endif %}
                            </ul>
                        </li>
                    {% endif %}

                    <!-- Events drop down menu-->
                    <li class="nav-item dropdown align-items-center text-center">
                        <button class="btn btn-primary dropdown-toggle custom-drop-down-menu" type="button" id="dropdownMenuButtonEvents" data-bs-toggle="dropdown" aria-expanded="false">
                            Events
                        </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButtonEvents">
                                <a class="dropdown-item custom-drop-down-element" href="/search">Event Search</a>
                                {% if user.is_authenticated and role != 2 %}
                                    <a class="dropdown-item custom-drop-down-element" href="/upcoming">Upcoming Events</a>
                                    <a class="dropdown-item custom-drop-down-element" href="/events/create">Create Event</a>
                                {% endif %}
                            </ul>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <button class="btn btn-primary dropdown-toggle custom-drop-down-menu" type="button" id="dropdownMenuButtonEvents" data-bs-toggle="dropdown" aria-expanded="false">
                            Organizations
                        </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButtonEvents">
                                <a class="dropdown-item custom-drop-down-element" href="/search/organization">Organization Search</a>
                                {% if user.is_authenticated and role != 2 %}
                                    <a class="dropdown-item custom-drop-down-element" href="/organizations/create">Create Organization</a>
                                {% endif %}
                            </ul>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <!-- Log out button -->
            {% if user.is_authenticated %}
                <a class="nav-item mx-2 log-button" href="{% url 'logout' %}">Log out</a>
            {% else %}
                <a class="nav-item mx-2 log-button" href="{% url 'social:begin' 'google-oauth2' %}">Log in</a>
            {% endif %}

        </div>
        <div class="toggle-switch">
            <label class="switch-label">
                <input type="checkbox" class="checkbox" id ="theme-toggle">
                <span class="slider"></span>
            </label>
        </div>  
    </nav>

    <header>

    </header>

    <main>
        {% block content %}
        <!-- will add other html views here in their files -->
        {% endblock %}
    </main>

    <footer class="footer">
        <div class="container" style="min-height: 50px">
            Copyright © 2024 UVA CS 3240 Team B-11. All Rights Reserved.
            This system is a class project and is not monitored. Please refrain from submitting real information.
        </div>
    </footer>
    <script>
    const toggleSwitch = document.getElementById('theme-toggle');
    const currentTheme = localStorage.getItem('theme') || 'light';
    document.documentElement.setAttribute('data-theme', currentTheme);
    toggleSwitch.checked = currentTheme === 'light'; 
    toggleSwitch.addEventListener('change', () => {
        const theme = toggleSwitch.checked ? 'light' : 'dark';
        document.documentElement.setAttribute('data-theme', theme);
        localStorage.setItem('theme', theme); 
    });
    </script>
</body>
</html>

myaccount/templates/myaccount/landingpage.html
{% extends "myaccount/base.html" %}

{% block title %}
    Poll Results
{% endblock %}
{% block content %}
<head>
    <title>Cavalier Connect</title>
</head>
<body>
    <main class="landing">
        <div class="overlay">
            <h1 class="landing-title">Cavalier Connect</h1>
            {% if user.is_authenticated %}
            <p style = "text-transform: capitalize; font-weight: 600;">Welcome, {{ user.first_name }} {{ user.last_name }}!</p>
            <!-- Events Container -->
            {% if user.role != 2 %}
                <div class="events-container">
                    <h2>My Events: <a class ="expand-event-view" href="/?key=1">See All Past Events</a></h2>
                    {% if my_events|length > 0 %}
                        <ul>
                            {% for e in my_events %}
                            <li><a class = "event_item" href="{% url 'events:view_event' e.pk %}">
                                Event: {{ e.title }}</a></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    <h2>Upcoming Events: <a class="expand-event-view"  href="/?key=2">See All Past Events</a></h2>
                    {% if upcoming_events|length > 0 %}
                        <ul>
                            {% for event_info in upcoming_events %}
                            <li><a class = "event_item" href="{% url 'events:view_event' event_info.event_pk %}">
                                {{ event_info.title }} - Status: {{ event_info.status }}</a></li>
                            {% endfor %}
                        </ul>
                        {% else %}
                        <p>You have not been invited to any events!</p>
                    {% endif %}
                    <h2>Create an Event:</h2>
                    <a class="orange-btn" href="{% url 'events:create_event' %}">Create Event</a>
                </div>
            {% else %}
                <div class="events-container d-flex flex-column justify-content-center text-center">
                    <a class="event_item" href="{% url 'pma' %}">PMA Dashboard</a>
                </div>
            {% endif %}
        </div>
        {% else %}
        <a class="google-button" href="{% url 'social:begin' 'google-oauth2' %}">
            <img src="https://upload.wikimedia.org/wikipedia/commons/c/c1/Google_%22G%22_logo.svg" alt="Google Logo" class="google-logo">
            Get Started
        </a>
    </div>
        {% endif %}
    </main>
</body>
{% endblock %}

myaccount/templates/myaccount/notification_setup.html
{% extends "myaccount/base.html" %}

{% block title %}
    Notification Settings
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
{% if user.phone_number %}
<div style="margin: 50px"></div>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-lg-10 col-xl-8 mx-auto">
            <div class="my-4">
                <h5 class="mb-0 mt-5" style="color:var(--blue-color)">Notifications Settings</h5>
                <p>Select the notification type(s) you want to receive!</p>
                <hr class="my-4" />
                <strong class="mb-0" style="color:var(--blue-color)">General</strong>
                <p>Please select a notification type</p>
                <form method="POST" action="{% url 'notification_settings' %}">
                {% csrf_token %}
                    <div class="list-group mb-5 shadow">
                        <div class="list-group-item">
                            <div class="row align-items-center">
                                <div class="col">
                                    <strong class="mb-0" style="color:var(--blue-color)">Email Notification</strong>
                                    <p class="mb-0" style="color:var(--text-color)">Recieve email notification on event invites/requests!</p>
                                </div>
                                <div class="col-auto">
                                    <div class="custom-control custom-switch">
                                        <input type="checkbox" class="custom-control-input" id="alert1" name ="email_notifications"{% if preferences.email_notifications %}checked {% endif %} />
                                        <span class="custom-control-label"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="list-group-item">
                            <div class="row align-items-center">
                                <div class="col">
                                    <strong class="mb-0" style="color:var(--blue-color)">SMS Notification</strong>
                                    <p class="mb-0" style="color:var(--text-color)">Recieve notification to mobile number regarding event activities!</p>
                                </div>
                                <div class="col-auto">
                                    <div class="custom-control custom-switch">
                                        <input type="checkbox" class="custom-control-input" id="alert2" name ="sms_notifications"{% if preferences.sms_notifications %} checked {% endif %} />
                                        <span class="custom-control-label"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="update-profile-btn d-block">Save Changes</button>
                    <a class = "update-profile-btn d-block mt-3 text-center" href="{% url 'myaccount' %}">Return</a>
                </form>
            </div>
        </div>
    </div>
    </div>
{% else %}
<div class="text-center d-flex flex-column align-items-center" style = "margin-top: 300px; padding: 10px;">
    <h4 style="color: var(--blue-color);">You need to verify your phone number first to continue.</h4>
    <a href="/myaccount" class="orange-btn w-25 mt-3">Return</a>
</div>
{% endif %}
{% else %}
<div class="text-center mt-5">
    <h4 style="color: var(--blue-color);">You are not logged in.</h4>
    <p>Please sign in with Google to continue.</p>
    <a href="{% url 'social:begin' 'google-oauth2' %}" class="google-sign-in-button">Sign in with Google</a>
</div>
{% endif %}
{% endblock %}